Setting activeArea from props
PEM-Humboldt/mibloque pull request #39
Opened 2019-11-26 17:52 UTC by alegnaaived

2019-11-26 19:19 UTC, cazapatamar approved these changes

2019-11-26 19:29 UTC, erikasv requested changes

2019-11-26 19:29 UTC, erikasv commented on src/IndicatorsDash.jsx
> +    console.log(activeArea);
Remove console.log

2019-11-27 12:57 UTC, erikasv approved these changes

2019-11-27 14:46 UTC, merged