Tree map data structure
PEM-Humboldt/mibloque pull request #55
Opened 2019-12-10 23:40 UTC by alegnaaived

2019-12-11 21:08 UTC, cazapatamar approved these changes
Solve the conflicts before merge

2019-12-19 21:19 UTC, erikasv requested changes
Also please:
1. Change colors according to Cesar request
1. Fix tooltip color and size
1. Add Ha values to the graph

2019-12-19 21:19 UTC, erikasv commented on src/IndicatorCard.jsx
> +
remove spaces

2019-12-23 21:07 UTC, cazapatamar approved these changes

2019-12-24 14:19 UTC, cazapatamar approved these changes

2019-12-24 16:45 UTC, erikasv approved these changes

2019-12-24 17:20 UTC, cazapatamar approved these changes

2019-12-24 17:21 UTC, merged