Fix column chart
PEM-Humboldt/mibloque pull request #58
Opened 2019-12-16 18:35 UTC by erikasv

2019-12-16 19:29 UTC, alegnaaived requested changes

2019-12-16 19:29 UTC, alegnaaived commented on src/graphs/GraphLoader.jsx
> +  options,
Please add information about options use

2019-12-16 19:52 UTC, erikasv commented on src/graphs/GraphLoader.jsx
> +  options,
fixed. Also added other minor fixes

2019-12-18 14:47 UTC, cazapatamar approved these changes

2019-12-18 14:56 UTC, alegnaaived approved these changes

2019-12-18 14:57 UTC, merged